### ISSUE TITLE
Roadmap to 0.2.0 🎉

### ISSUE THREAD

**Issue by n9inee** [neinteen/poke#1]
## Roadmap to 0.2.0 🎉

As you might have noticed, while being perfectly usable for creating files, poke right now is clunky and lacking core functionality.
Moving forward I've decided to make this roadmap. Since this is my first project on GitHub and also the first project I really aim to finish and maintain, this will be the best way to keep a clear goal in mind and also stop me from doing small stupid mistakes.

I will incrementally implement these changes from 0.1.3 - 0.1.9, then I do some finishing touches and release 0.2.0, which is intended to be the final version. Other than bugfixes etc, I don't plan on adding features after this version, I will simply maintain it. (This might change in the future)

I hope that the few of you that are interested keep sticking around because I'm sure this will end up being an awesome small cli app :)

## Planned Changes:

- [x] Create/delete files [impl. 0.1.1]
- [x] Change access/modification time [impl. 0.1.1]
- [x] Use reference file [impl. 0.1.2]
- [x] General rewrite/restructure [impl 0.1.2]
- [x] Date command (from human string using chrono_english) [planned 0.1.3]
- [ ] Start publishing binary releases
- [x] Move code to lib file
- [ ] Support unix like path syntax (../some_folder/file.txt) [planned 0.1.4]
- [ ] Support creating directories (avoid having to cd, just dir/file.txt) [planned 0.1.4]
- [ ] Support moving files [planned 0.1.x]
- [ ] Support creation time change (custom crate or filetime fork?) [planned 0.1.x]

These changes are planned to happen in around a months time. Due to my life being pretty busy, I can't promise anything tho.
Anyways thanks to everyone that took the time to look at this and maybe decided to install it or wait for the final product :)!

UPDATE: I will no longer maintain this project or update it. It was a fun thing to do but I see no point in moving this any further.
